//=========================================================
// src/InitDevice.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include "K1921VK035.h"
#include "retarget_conf.h"

// FUNCTIONS
static void PCA0_Init(void);
static void Init_Clocks(void);
static void Init_Ports(void);
static void Init_Timers(void);
static void Init_SMBus(void);
static void Init_Interrupts(void);

//==============================================================================
// Init_Peripherals
//==============================================================================
static void Init_Peripherals(void) {
	SystemCoreClockUpdate();
	retarget_init();
	
	// Save the SFRPAGE
	uint8_t SFRPAGE_save = SFRPAGE;

	//Init Watchdog
	PCA0_Init();

	//Init clocks
	// Init_Clocks();

	//Init ports
	// Init_Ports(); // TODO: Check on schematic

	//Init all used timers
	Init_Timers();

	//Init SMBus (I2C slave and master)
	Init_SMBus();

	//Init interrupts
	Init_Interrupts();

	//Start precision temperature sensor
	Start_temperature_sensor();

	// Restore the SFRPAGE
	SFRPAGE = SFRPAGE_save;
}

//-----------------------------------------------------------------------------
// PCA0_Init
//-----------------------------------------------------------------------------
// This function disables the watchdog timer. TODO check on tests
static void PCA0_Init (void)
{
	
}

//================================================================================
//Init clocking system
// This function initializes the system clock to use the internal HF oscillator at 49.0 MHz.
static void Init_Clocks(void) {
	// ”????????? ??????? ??????????? (????????????????) ?????????? = 49.0 ?v?
	OSCICN = 0x80;		// Enable HF oscillator

	PFE0CN    |= 0x20;		// Enable Prefetch Engine
	FLSCL     |= 0x10;		// Flash Read Timing: SYSCLK <= 50 MHz

	CLKSEL = 0x03;		// clock source is HF oscillator (without divider)

}
//================================================================================

//================================================================================
// Init Port IO pins
static void Init_Ports(void) {
	// ----- Port 0
	//P0.0 .. P0.3 - reserved
	//P0.1 - test pin (output)
	// - P0.4, P0.5 pins are used for SMBus0 (I2C slave)
	// - P0.6, P0.7 pins are used for SMBus1 (I2C master)
	P0MDIN = 0xFF;	//All pins are digital
	P0MDOUT = P0MDOUT_B1__PUSH_PULL;	//All pins are open-drain, except Test_pin
	P0SKIP = 0x0F;		//skip 0..3 pins
	P0MASK = 0x00;		//all pins are ignored by Match

	// ----- Port 1
	// - P1.0, P1.1 pins are used as M-RS0 and M-RS1 (outputs to CDR chip)
	// - P1.2 - reserved
	// - P1.3 - TX_FAULT (input from CDR)
	// - P1.4 - TX_DISABLE (input from ext. connector)
	// - P1.5 - LOS (input from CDR)
	// - P1.6, P1.7 pins are used as RS0 and RS1 (inputs from ext. connector)
	P1MDIN = 0xFF;	//All pins are digital
	P1MDOUT = 0x00;	//All pins are open-drain
	P1SKIP = 0x00;

	// ----- Port 2
	//not used

	//SMBus 0 I/O routed to Port pins, all other peripherals are not used
	XBR0 = XBR0_SMB1E__ENABLED | XBR0_SMB0E__ENABLED;	// Enable the SMBus0 & SMBus1 on the XBAR

	XBR1 = XBR1_XBARE__ENABLED;                        // Enable the XBAR and weak pull-ups

}
//================================================================================

//================================================================================
// TIMER_SETUP_0_enter_DefaultMode_from_RESET
static void Init_Timers(void) {
	TMR0->CTRL_bit.INTEN = 0;
	
	TMR1->CTRL_bit.INTEN = 1;
	TMR1->CTRL_bit.ON = 1;
	
	uint32_t Temp_u32;
	SFRPAGE = 0x00;
	// SCA (Timer 0/1 Prescale) = SYSCLK_DIV_4 (System clock divided by 4.)
	// Timer 0 and Timer 1 use prescaled clock (SCA)
	// Timers 2 and 3 (H and L) use appropriate TnXCLK
	CKCON = CKCON_SCA__SYSCLK_DIV_4 | CKCON_T0M__PRESCALE | CKCON_T1M__PRESCALE
			| CKCON_T2MH__EXTERNAL_CLOCK | CKCON_T2ML__EXTERNAL_CLOCK
			| CKCON_T3MH__EXTERNAL_CLOCK | CKCON_T3ML__EXTERNAL_CLOCK;

	// CKCON1 - T4 use appropriate TnXCLK, T5 use appropriate SYSCLK
	CKCON1 = CKCON1_T4MH__EXTERNAL_CLOCK | CKCON1_T4ML__EXTERNAL_CLOCK
			| CKCON1_T5MH__SYSCLK | CKCON1_T5ML__SYSCLK;

	// Timer 0 use Mode 1 (16-bit Counter/Timer)
	// Timer 1 use Mode 2 (8-bit Counter/Timer with Auto-Reload)
	// T0 and T1 used as timers w/o GATE
	TMOD = TMOD_T0M__MODE1 | TMOD_T1M__MODE2 | TMOD_CT0__TIMER
			| TMOD_GATE0__DISABLED | TMOD_CT1__TIMER | TMOD_GATE1__DISABLED;

	// Timers 0 and 1 clocked by SYSCLK/4
	//------- Timer0

	//------- Timer1
	// Timer1 is used for SMBus0 clock source
	// and timer overflow freq = SMB freq * 3
	Temp_u32 = (SYSCLK_FREQ / 4) / (SMB_FREQ * 3);
	Temp_u32 = (256 - Temp_u32) & 0xFF;
	TH1 = Temp_u32;
	TL1 = Temp_u32;
    TCON_TR1 = 1;                         // Start Timer1
	//-----

	//------- Timer2
	// Timer2 is used to generate 10 ms periodic interrupt
	// Timer2 use SYSCLK / 12, 16-bit reload mode, don't start yet
	TMR2CN = 0x00;
	//We need to count 10ms (100 Hz)
	Temp_u32 = (65536 - ((SYSCLK_FREQ / 12) / 100)) & 0xFFFF;
	TMR2RLH = (Temp_u32 >> 8) & 0xFF;
	TMR2RLL = Temp_u32 & 0xFF;
	TMR2CN_TR2 = 1;                         // Start Timer2
	//-----

	//------- Timer3
	//-----

	//------- Timer4
	//-----

	//------- Timer5
	// Timer5 is clocked by sysclk and used for SMBus1 clock source
	// and timer overflow freq = SMB freq * 3
	SFRPAGE = TIMER5_PAGE;
	Temp_u32 = (SYSCLK_FREQ) / (SMB_FREQ * 3);
	Temp_u32 = (65536 - Temp_u32) & 0xFFFF;
	TMR5RLH = (Temp_u32 >> 8) & 0xFF;
	TMR5RLL = Temp_u32 & 0xFF;
	TMR5CN = TMR5CN_TR5__RUN;	//Start timer5 in 16-bit auto-reload mode
	SFRPAGE = 0;
	//-----
}
//================================================================================

//================================================================================
// Init SMBus0 (I2C slave) and SMBus1 (I2C master)
static void Init_SMBus(void) {

//	SMBTC = 0x00;	//default values (no SMBus pin swapping)
	SMBTC = SMBTC_SMB1SWAP__SDA_HIGH_PIN;	//default values (no SMBus pin swapping)


	//SMBus0
	SFRPAGE = 0x00;
	// Use Timer1 overflows as SMBus clock source; Enable slave mode;
	// Enable setup & hold time extensions; Enable SMBus Free timeout detect;
	// Disable SCL low timeout detect;
	SMB0CF	= SMB0CF_SMBCS__TIMER1 | SMB0CF_SMBFTE__FREE_TO_ENABLED |
			SMB0CF_SMBTOE__SCL_TO_DISABLED | SMB0CF_EXTHOLD__ENABLED |
			SMB0CF_INH__SLAVE_ENABLED;
	SMB0ADM	= 0xFE;		// Disable HW address acknowlendge
	SMB0CF |= SMB0CF_ENSMB__ENABLED;		// Enable SMBus0;

	//SMBus1
	SFRPAGE = SMBUS1_PAGE;
	// Use Timer5 overflows as SMBus clock source; Master mode (Disable slave mode);
	// Enable setup & hold time extensions; Enable SMBus Free timeout detect;
	// Disable SCL low timeout detect;
	SMB1CF	= SMB1CF_SMBCS__TIMER5 | SMB1CF_SMBFTE__FREE_TO_ENABLED |
			SMB1CF_SMBTOE__SCL_TO_DISABLED | SMB1CF_EXTHOLD__ENABLED |
			SMB1CF_INH__SLAVE_DISABLED;
	//For master ADR and ADM registers are not used
	SMB1CF |= SMB1CF_ENSMB__ENABLED;		// Enable SMBus1;
	SFRPAGE = 0;

}
//================================================================================

//================================================================================
static void Init_Interrupts(void) {
	SFRPAGE = 0x00;
	// EIE1 - Extended Interrupt Enable 1
	// Enable SMB0 (I2C slave) interrupts
	// Disable Timer3, ADC0, Match, CP0, CP1, PCA0 interrupts
	EIE1 = EIE1_EADC0__DISABLED | EIE1_EWADC0__DISABLED | EIE1_ECP0__DISABLED
			| EIE1_EMAT__DISABLED | EIE1_EPCA0__DISABLED
			| EIE1_ESMB0__ENABLED | EIE1_ET3__DISABLED;
//	| EIE1_ESMB0__DISABLED | EIE1_ET3__DISABLED;

	// EIE2 - Extended Interrupt Enable 2
	// Disable SMB1 (I2C master) interrupt (SMB1 works in this project without interrupt)
	// PTS, Timer4, Timer5 interrupts
	EIE2 = EIE2_EPTS__DISABLED | EIE2_ET4__DISABLED
			| EIE2_ET5__DISABLED | EIE2_ESMB1__DISABLED;
//			| EIE2_ET5__DISABLED | EIE2_ESMB1__ENABLED;

	// All int priority registers uses default values

	// IE
	// Enable each interrupt according to its individual mask setting
	// Enable Timer2 interrupt
	// Disable ExtInt0, ExtInt1, SPI0, Timer0, Timer1, UART0 interrupts
	IE = IE_EA__ENABLED | IE_EX0__DISABLED | IE_EX1__DISABLED
			| IE_ESPI0__DISABLED | IE_ET0__DISABLED | IE_ET1__DISABLED
			| IE_ET2__ENABLED | IE_ES0__DISABLED;

}
//================================================================================

//================================================================================
static void Start_temperature_sensor(void) {
	//Start new measurement
	SFRPAGE = PTEMPCFG_PAGE;
	TS0CN = TS0CN_TSSTRT__START1;
	TS0CN = TS0CN_TSSTRT__START2;

	SFRPAGE = 0x00;	//restore default page
}
//================================================================================

//================================================================================
//Read measurement if data is ready and start new measurement
static void Read_temperature_sensor(void) {
	//Check data ready flag
	SFRPAGE = PTEMPCFG_PAGE;
	if(TS0CN & TS0CN_TSDN__SET) {
		//Data is ready -> read result
		SFRPAGE = PTEMPDAT_PAGE;
		Temp_u16 = (TS0DATH << 8) | TS0DATL;
		A2Up_Page.var.CPU_Temp = Temp_u16;

		//Start new measurement
		SFRPAGE = PTEMPCFG_PAGE;
		TS0CN = TS0CN_TSSTRT__START1;
		TS0CN = TS0CN_TSSTRT__START2;
	}
	SFRPAGE = 0x00;	//restore default page
}
//================================================================================

